# Generated by Django 5.0.3 on 2024-03-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_employee_department_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='type',
            new_name='device_type',
        ),
    ]
