# Generated by Django 5.0.3 on 2024-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_type_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='assigned_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='assigned_condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='returned_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='returned_condition',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='specification',
            field=models.TextField(),
        ),
    ]
