# Generated by Django 5.0.3 on 2024-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_device_assigned_alter_allocation_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
