# Generated by Django 5.0.3 on 2024-03-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_allocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.employee'),
        ),
    ]
