# Generated by Django 5.0.3 on 2024-03-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_device_current_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='current_holder',
        ),
    ]
