# Generated by Django 5.0.3 on 2024-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_device_current_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned',
            field=models.BooleanField(default=True),
        ),
    ]
