# Generated by Django 5.0.3 on 2024-03-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_device_user_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='current_holder',
            field=models.ForeignKey(default='Company', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.employee'),
        ),
    ]
